#!/usr/bin/env bash
#
#
VERSION="1.0.6"
cp -f nexus-updater/*.html /usr/local/share/nexus
sudo cp -f nexus-updater/nexus-updater.desktop /usr/local/share/applications/
sudo cp -f nexus-updater/*.sh /usr/local/sbin/
#[ -f $HOME/.local/share/applications/updatepi.desktop ] && rm -f $HOME/.local/share/applications/updatepi.desktop
exit 0
