#!/usr/bin/env bash
#
#
VERSION="1.0.3"
sudo cp -f $SRC_DIR/nexus-updater/nexus-updater.desktop /usr/local/share/applications/
sudo cp -f $SRC_DIR/nexus-updater/*.sh /usr/local/sbin/
#[ -f $HOME/.local/share/applications/updatepi.desktop ] && rm -f $HOME/.local/share/applications/updatepi.desktop
